# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_processor.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'image_processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15image_processor.proto\x12\x0eimageprocessor\"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"(\n\rImageResponse\x12\x17\n\x0fprocessed_image\x18\x01 \x01(\x0c\x32]\n\x0eImageProcessor\x12K\n\x0cProcessImage\x12\x1c.imageprocessor.ImageRequest\x1a\x1d.imageprocessor.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=41
  _globals['_IMAGEREQUEST']._serialized_end=70
  _globals['_IMAGERESPONSE']._serialized_start=72
  _globals['_IMAGERESPONSE']._serialized_end=112
  _globals['_IMAGEPROCESSOR']._serialized_start=114
  _globals['_IMAGEPROCESSOR']._serialized_end=207
# @@protoc_insertion_point(module_scope)
